const API_BASE_URL_DEVELOPMENT = "https://localhost:7146/api";
const API_BASE_PRODUCTION = "";

const ENDPOINTS_DRIVERS = {
  GET_ALL_DRIVERS: "drivers",
};
const ENDPOINTS_ORDERS = {
  GET_ALL_ORDERS: "orders",
};

const ENDPOINTS_VEHICLES = {
  GET_ALL_VEHICLES: "vehicles",
  DELETE_VEHICLE: "vehicles",
  ADD_VEHICLE: "",
  UPDATE_VEHICLE: "",
};
const ENDPOINTS_BRANDS = {
  GET_ALL_BRANDS: "VehicleBrands",
};
const ENDPOINTS_MODELS = {
  GET_ALL_MODELS: "VehicleModels",
};
const development = {
  API_URL_GET_ALL_DRIVERS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_DRIVERS.GET_ALL_DRIVERS}`,

  API_URL_GET_ALL_ORDERS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_ORDERS.GET_ALL_ORDERS}`,

  API_URL_GET_ALL_VEHICLES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_VEHICLES.GET_ALL_VEHICLES}`,
  API_URL_DELETE_VEHICLE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_VEHICLES.DELETE_VEHICLE}`,

  API_URL_GET_ALL_BRANDS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_BRANDS.GET_ALL_BRANDS}`,
  API_URL_GET_ALL_MODELS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_MODELS.GET_ALL_MODELS}`,
};
const production = {
  API_URL_GET_ALL_VEHICLES: ` `,
};
const Constants =
  process.env.NODE_ENV === "development" ? development : production;
export default Constants;
